version: '3'
services:
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
  
  node-app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:5000"